name: 路线异常
description: 自动导航未按正常路线走
labels: [路线错误]
title: "[路线错误] "
body:
  - type: textarea
    id: bug
    attributes:
      label: 问题描述
      description: 说明你遇到的路线问题
    validations:
      required: true
  - type: checkboxes
    id: role
    attributes:
      label: 是否使用三月七跑图
      description: 未使用三月七跑图的反馈不会别受理
      options:
        - label: 是
        - label: 否