name: 更新地图文件

on:
  push:
    branches: [ map ]
    paths:
      - 'map/**'

  workflow_dispatch:
  
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
